import { ViewStyle, TextStyle, ImageStyle } from 'react-native';

export default interface IHomeStyles {
  container: ViewStyle,
  page: ViewStyle,
  header: ViewStyle,
  headerLogo: ImageStyle,
  headerTitle: TextStyle,
  main: ViewStyle,
  section: ViewStyle,
  flexRow: ViewStyle,
  flexColumn: ViewStyle,
  flexSpaceAround: ViewStyle,
  flexSpaceBetween: ViewStyle,
  modal: ViewStyle,
  modalBox: ViewStyle,
  modalBlock: ViewStyle,
  modalHeader: ViewStyle,
  modalHeaderText: TextStyle,
  modalContent: ViewStyle,
  modalFooter: ViewStyle,
  btn: ViewStyle,
  btnDefault: ViewStyle,
  btnSuccess: ViewStyle,
  flexFill: ViewStyle,
  viewBordered: ViewStyle,
  textBordered: TextStyle,
  textCenter: TextStyle,
  textRight: TextStyle,
  textWhite: TextStyle
}